Update README.md
Netuitive/statsd-netuitive-backend pull request #7
Opened 2021-02-08 13:15 UTC by rbellary-vi

updating URL

2021-02-08 13:36 UTC, TheConnMan requested changes

2021-02-08 13:36 UTC, TheConnMan commented on README.md
> +For more information on the StatsD integration with Netuitive, see our [help docs](https://docs.metricly.com/integrations/etsy-statsd/), or contact Netuitive support at [support@netuitive.com](mailto
Support link.

2021-02-08 13:36 UTC, TheConnMan commented on README.md
>  Netuitive offers a backend plugin for [StatsD](https://github.com/etsy/statsd) that allows you to monitor your StatsD metric data with [Netuitive](https://www.netuitive.com).
netuitive.com

2021-02-09 11:35 UTC, rbellary-vi reviewed
changing the support link

2021-02-09 11:36 UTC, closed without merging